Internal Server Error: /
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/waze_poi/venues/views.py", line 17, in get
    return render(request, "home.html", locals())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
    output = self.filter_expression.resolve(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 708, in resolve
    obj = self.var.resolve(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 849, in resolve
    value = self._resolve_lookup(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 911, in _resolve_lookup
    current = current()
  File "/home/edx/waze_poi/venues/models.py", line 63, in get_position
    print self.position.longitude + ' ' + self.position.latitude
TypeError: unsupported operand type(s) for +: 'Decimal' and 'unicode'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/waze_poi/venues/views.py", line 17, in get
    return render(request, "home.html", locals())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse some characters: venue.get_position|()| | default:"Sin Descripci\xf3n"
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 213, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 44, in get_form
    form_class = self.get_form_class()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 129, in get_form_class
    "the 'fields' attribute is prohibited." % self.__class__.__name__
ImproperlyConfigured: Using ModelFormMixin (base class of CreateVenue) without the 'fields' attribute is prohibited.
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 213, in get
    return super(BaseCreateView, self).get(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 174, in get
    return self.render_to_response(self.get_context_data())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 93, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 44, in get_form
    form_class = self.get_form_class()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 109, in get_form_class
    "Specifying both 'fields' and 'form_class' is not permitted."
ImproperlyConfigured: Specifying both 'fields' and 'form_class' is not permitted.
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 48, in select_template
    return engine.get_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 16: 'trans', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 217, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 163, in form_valid
    return super(ModelFormMixin, self).form_valid(form)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 79, in form_valid
    return HttpResponseRedirect(self.get_success_url())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 154, in get_success_url
    "No URL to redirect to.  Either provide a url or define"
ImproperlyConfigured: No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/edx/waze_poi/venues/views.py", line 17, in get
    return render(request, "home.html", locals())
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '&&' from '&&'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: venues/venue_list.html
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 60, in __str__
    return self.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 63, in render
    return mark_safe('\n'.join(chain(*[getattr(self, 'render_' + name)() for name in MEDIA_TYPES])))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 70, in render_js
    ) for path in self._js
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 92, in absolute_path
    return static(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'django_select2/django_select2.js'
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 60, in __str__
    return self.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 63, in render
    return mark_safe('\n'.join(chain(*[getattr(self, 'render_' + name)() for name in MEDIA_TYPES])))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 70, in render_js
    ) for path in self._js
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 92, in absolute_path
    return static(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'django_select2/django_select2.js'
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 60, in __str__
    return self.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 63, in render
    return mark_safe('\n'.join(chain(*[getattr(self, 'render_' + name)() for name in MEDIA_TYPES])))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 70, in render_js
    ) for path in self._js
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 92, in absolute_path
    return static(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'django_select2/django_select2.js'
Internal Server Error: /venue/new
Traceback (most recent call last):
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 60, in __str__
    return self.render()
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 63, in render
    return mark_safe('\n'.join(chain(*[getattr(self, 'render_' + name)() for name in MEDIA_TYPES])))
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 70, in render_js
    ) for path in self._js
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/forms/widgets.py", line 92, in absolute_path
    return static(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 166, in static
    return StaticNode.handle_simple(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/templatetags/static.py", line 117, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/edx/.virtualenvs/waze/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'django_select2/django_select2.js'
